### ISSUE TITLE
Flashed firmware 16.8.8

### ISSUE THREAD

**Issue by bobyal1** [Saturn49/wecb#14]
New firmware flashed successfully. However I don't see a management IP to access web UI.

Is there any physical H/W button configuration to revert firmware?

Any suggestions//

**Comment by drkfox46** [comment]
There isn't a physical button to revert the firmware, but you can connect to the serial port with a USB to uart converter as jhujhujhujhu describes. Then when the device is booting you need to press a certain key to stop the boot (I think the escape key) and about 5 options will pop up, one of them is to revert the firmware.

**Comment by bobyal1** [comment]
Thank you for your inputs.
It may be a coincidence, I just connected to console and figured that IP was not assigned. I assigned a IP and accessed the web and reverted the firmware.
Thank you to jhujhujhujhu for his details and images for accessing the console.
Thanks

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 9, 2021 at 12:22 PM, drkfox46<notifications@github.com> wrote:   


There isn't a physical button to revert the firmware, but you can connect to the serial port with a USB to uart converter as jhujhujhujhu describes. Then when the device is booting you need to press a certain key to stop the boot (I think the escape key) and about 5 options will pop up, one of them is to revert the firmware.
